### ISSUE TITLE
cannot open the connection

### ISSUE THREAD

**Issue by sjanssen2** [aametwally/MetaLonDA#8]
Hi,
I am trying to run your wonderful tool on ~90 features, 1200 samples. After a while, I get the following error: 
```
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
Calls: metalondaAll ... write.csv -> eval.parent -> eval -> eval -> write.table -> file
```
Unfortunately, I don't know how to make `R` print line numbers or a more elaborate stack trace. I suspect the number of open file handles is exceeded. Do you know how to raise this number?

**Comment by sjanssen2** [comment]
Limit seems to be set to 128 - 3 available connections: https://github.com/HenrikBengtsson/Wishlist-for-R/issues/28

**Comment by sjanssen2** [comment]
I spiked `cat(nrow(showConnections()))` into the metalonda function, which always shows 0 - so it looks like all connections are properly closed each time.

**Comment by aametwally** [comment]
Hi Stefan,

The rationale behind having the double prefix in saving figures statements is because I thought it would be easier for users to save all generated figures in one directory. Given that MetaLonDA generates ~5 files for each tested features, it'd be a bit distracting if all of these figures are saved in the current directory. Coming from the C/C++ as well, I think your suggestion is great though. In the next version, I'll add one parameter for specifying the output path and another parameter for the prefix.
